### ISSUE TITLE
SWF failed!

### ISSUE THREAD

**Issue by CriztianiX** [umegaya/lua-aws#18]
Trying to test swf i get:
                                                                     
swf:v[2012-01-25]:      Something wrong in the request  nil     {"__type":"com.amazon.coral.service#IncompleteSignatureException","message":
"Date must be in ISO-8601 'basic format'. Got '1442252505'. See http://en.wikipedia.org/wiki/ISO_8601"}

**Comment by umegaya** [comment]
@CriztianiX I think aws-sdk-js's data is something wrong. it contains timestampFormat metadata, and its unixTimestamp. can you remove following line and see it goes well?
https://github.com/umegaya/lua-aws/blob/master/lua-aws/services/specs/swf-2012-01-25.min.json#L11

if problem does not solved, please give me your testcase.

**Comment by CriztianiX** [comment]
My test case:
```lua
AWS = AWS.new({
    accessKeyId = config.aws.access_key,
    secretAccessKey = config.aws.access_secret,
    region = config.aws.region,
    endpoint = config.aws.endpoint,
    preferred_engines = {
      json = "cjson",
      fs = "lfs"
    }
})

local res,err = AWS.SWF:api():listDomains()
```

swf:v[2012-01-25]: Something wrong in the request nil {"__type":"com.amazon.coral.service#IncompleteSignatureException","message":
"Date must be in ISO-8601 'basic format'. Got '1442252505'. See http://en.wikipedia.org/wiki/ISO_8601"}


Removing https://github.com/umegaya/lua-aws/blob/master/lua-aws/services/specs/swf-2012-01-25.min.json#L11

i get:
swf:v[2012-01-25]:      Something wrong in the request  nil     {"__type":"com.amazon.coral.validate#ValidationException","
message":"1 validation error detected: Value null at 'registrationStatus' failed to satisfy constraint: Member must not be 
null"}

**Comment by umegaya** [comment]
@CriztianiX that's good. I have applied this fix (and test also runs correctly)
