### ISSUE TITLE
Cant decode json body in sqs message

### ISSUE THREAD

**Issue by CriztianiX** [umegaya/lua-aws#30]
Hey, I'm currently sending a json-string in the sqs body message.
I'm having troubles when i try to decode this string message, seems to be that the xml contains 
\&quot; in each attribute of the message body.
To handle this my poor solution was to do a base64.encode in a string, and a base.decode

**Comment by umegaya** [comment]
@CriztianiX hi, sorry for late reply, I will investigate the reason. can you provide example payload which causes problem?

**Comment by CriztianiX** [comment]
Something like this:

’’’lua
MessageBody = dkjson.encode({
  page: 1, model = "user"
})
’’’

**Comment by umegaya** [comment]
@CriztianiX maybe this is because xml response need to be unescape &***; please try above PR branch and give me feed back. thanks!

**Comment by CriztianiX** [comment]
Working!!!

**Comment by umegaya** [comment]
thanks!
