### ISSUE TITLE
Athena and Firehose support?

### ISSUE THREAD

**Issue by Madhu1512** [umegaya/lua-aws#43]
Can you add support for AWS Athena and Firehose?

**Comment by umegaya** [comment]
@Madhu1512 I added these APIs at #44. but just check about listXXX apis. can you try it with your workflow and test it works? if you have a problem, please notice me your entire usecase, which greatly helps me to create more useful testcase.

**Comment by umegaya** [comment]
close this issue because no response to #43 for a while. please reopen this if you have a problem
