### ISSUE TITLE
lua-aws in Openresty

### ISSUE THREAD

**Issue by mthota15** [umegaya/lua-aws#46]
I am planning to use lua-aws module under Openresty environment. How to leverage the openresty http engine for aws api calls?

**Comment by umegaya** [comment]
hi, thank you for having interest in lua-aws!

there is http engine for the purpose. https://github.com/umegaya/lua-aws/blob/master/lua-aws/engines/http/lua-resty-http.lua and you should use it like following:

```
	local aws = AWS.new({
		accessKeyId = ...,
		secretAccessKey = ...,
		endpoint = ...,
		preferred_engines = {
                         http = 'lua-resty-http'
                },
	})

```

**Comment by umegaya** [comment]
FYI, currently lua-resty-http have this limitation. 
- s3 getObject output cannot write directly into file handle.

**Comment by mthota15** [comment]
Thanks @umegaya.
