### ISSUE TITLE
use IAM Credentials 

### ISSUE THREAD

**Issue by mthota15** [umegaya/lua-aws#47]
I am testing ecs api query on AWS EC2 where my IAM role has full permission to ECS api. But lua-aws is not able to use the IAM role. How to configure lua-aws to use IAM role?

local AWS = require ('lua-aws.init')
local Region = os.getenv('AWS_REGION') or 'us-east-1'
local aws = AWS.new({
    region = Region,
    endpoint = "https://ecs." .. Region .. ".amazonaws.com"
})

print("https://ecs." .. Region .. ".amazonaws.com")
local api = aws.ECS:api_by_version('2014-11-13')
ok, r = api:listClusters({
        maxResults = 10,
})

if not ok then
        assert(ok, r)
end

**Comment by umegaya** [comment]
I think IAM user have its own access key and secret key. then you can specify it via config object, like following:

```
	local aws = AWS.new({
		accessKeyId = YOUR_IAM_ROLE_ACCESS_KEY,
		secretAccessKey = YOUR_IAM_ROLE_SECRET_KEY,
		endpoint = ...,
       })
```

do you mean this way not working?

**Comment by mthota15** [comment]
I can do by creating IAM user and use accesskey and secret key for credentials but i am want to use IAM role for EC2 to load credential automatically.

Node.js SDK can do this: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-iam.html

**Comment by umegaya** [comment]
@mthota15 hi, thank you for the pointer, I create #49. that is what you need? if so, would you please check it works? otherwise please provide more detail spec.

**Comment by umegaya** [comment]
close this issue due to long time no response from original reporter, even if fix already provided.
@mthota15 if my fix (now can test with master branch) is not suitable for your use case, feel free to reopen this.
