### ISSUE TITLE
describeInstances with Instance ID does not work

### ISSUE THREAD

**Issue by aryajur** [umegaya/lua-aws#50]
Hi,
         I was trying out describeInstances by providing an array (as a lua table) of 1 instance ID. But it always returns all the instances. I tried initializing the array table from the 0 index but that does not work either. Has anyone tried this?

**Comment by umegaya** [comment]
@aryajur hi, I think this is my bug when port query serializer for ec2 from aws-sdk-js. can you try referenced branch and see it works? 

regards,

**Comment by aryajur** [comment]
Thanks for looking into it quickly. Yes this works well on the referenced branch.
