### ISSUE TITLE
Uprade the lua version.

### ISSUE THREAD

**Issue by meetme2meat** [umegaya/lua-aws#57]
Lua-aws has a current support for Lua 5.1 version. Can we get to work with lua-5.3+

**Comment by umegaya** [comment]
@meetme2meat  hi, thank you for having interest for lua-aws!

there seems some [attempt](https://github.com/umegaya/lua-aws#caveats-for-lua-53-user) to do so. 
if its not helpful for you, can you post problem detail you encount? I try to support if it does not make big change to core.

**Comment by umegaya** [comment]
@meetme2meat close this due to inactiveness. feel free to reopen if you have a problem. thanks!

**Comment by meetme2meat** [comment]
@umegaya a question before you do that.. how does one manually install bit (is it same as copy the bit.lua inside `/usr/local/lib/lua`)

**Comment by umegaya** [comment]
which os do you use? in osx, following steps work for me. 
1. download https://github.com/aryajur/bit/blob/master/src/bit.lua 
2. put it in /usr/local/lib/lua/5.3/ (if its not exists, create)

**Comment by meetme2meat** [comment]
@umegaya  Thanks
