### ISSUE TITLE
Bind Kinesis API

### ISSUE THREAD

**Issue by daurnimator** [umegaya/lua-aws#7]
Please bind Kinesis: https://aws.amazon.com/documentation/kinesis/

**Comment by umegaya** [comment]
thank you for request. I will work for it today.

**Comment by umegaya** [comment]
hi, I create PR #8 
it should be support basic kinesis API. 
see PR's caveat and if that is enough for you, please try in your environment. 
also read the caution and add proper configuration to keep compatibility. thanks!

**Comment by umegaya** [comment]
hmm, I want to go forward, so I have merged #8, and close this issue. when you test in your environment and have some problems, feel free to reopen this issue. thanks!

**Comment by daurnimator** [comment]
Sorry, I ended up using another library instead.
Thanks for working on this though :)
