### ISSUE TITLE
Add support for images in `CreateFunction`

### ISSUE THREAD

**Issue by styfle** [umegaya/lua-aws#78]
AWS Lambda just updated the CreateFunction request payload as seen in this commit: 

https://github.com/awsdocs/aws-lambda-developer-guide/commit/682401cbe5222517ce2789c69a2248cf0362ff41

In particular, I'm interested in `Code.ImageUri`, `ImageConfig`, and `PackageType`.

[![image](https://user-images.githubusercontent.com/229881/101642184-afdf7380-3a00-11eb-83e8-b6a98aff0f6f.png)](https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/doc_source/API_CreateFunction.md)

**Comment by umegaya** [comment]
@styfle thank you for suggestion! I will update API definition and test imageUrl is work

**Comment by umegaya** [comment]
@styfle sorry for late, I have updated API definition at #79 and can create/invoke function with ImageUrl with [payload like this](https://github.com/umegaya/lua-aws/blob/umegaya/issue-78/test/lambda.lua#L107) can you test the branch with your usage? 

regards,

**Comment by styfle** [comment]
@umegaya Thanks for the quick implementation!

I probably won't have time to test this feature for a week or so.

Feel free to merge and I'll report any outstanding problems in a new issue, thanks! 👍

**Comment by umegaya** [comment]
ok, I will merge related PR
