### ISSUE TITLE
Add support for Architectures in CreateFunction

### ISSUE THREAD

**Issue by styfle** [umegaya/lua-aws#80]
AWS Lambda just added support for Architectures in CreateFunction/UpdateFunction which can be `x86_64` or `arm64`.

- See commit: https://github.com/awsdocs/aws-lambda-developer-guide/commit/640845bd869baabd7086201321bef3a4c1497e84
- See announcement: https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/

**Comment by umegaya** [comment]
@styfle at PR #81 I have updated API definitions of lua-aws and add small test that confirm lua-aws can create ZipFile package with arm64 architecture. can you check the fix is useful for your purpose? thanks!

**Comment by styfle** [comment]
@umegaya Looks like that PR will solve this issue, thanks! 🙏

**Comment by umegaya** [comment]
@styfle glad to hear that. now I merged #81 and close the issue. feel free to reopen if any problem happens.
